language: node_js
node_js:
- 6
script: bash ./deploy.sh
env:
  global:
  - ENCRYPTION_LABEL: "19cb81709d6d"
  - SOURCE_BRANCH: "source"
  - TARGET_BRANCH: "master"
cache:
  directories:
  - node_modules
